version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: vverb_pgvector
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
      POSTGRES_DB: vverb
    ports:
      - "6262:5432"
    volumes:
      - ./init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgvector"]
      interval: 5s
      timeout: 5s
      retries: 5

# If you want to add more services (like test runner), you can do so here.