# workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev,pgvector]"

      # -------- Ruff lint --------
      - name: Ruff lint
        run: |
          ruff check src tests

      # -------- mypy type-check (relaxed) --------
      - name: mypy
        run: |
          mypy -p vverb --pretty --show-error-codes

      # -------- Run test suite --------
      - name: Run pytest
        env:
          PYTHONPATH: src
        run: |
          pytest -q